### ISSUE TITLE
Kan man enkelt se bakomliggande JSON i Litteraturbanken

### ISSUE THREAD

**Issue by salgo60** [spraakbanken/littb-frontend#23]
jmf SKBL
* sida https://www.skbl.se/sv/artikel/NaimaSahlbom
** har json https://www.skbl.se/sv/artikel/NaimaSahlbom.json

Jag synkar och städar just nu upp Wikidata <-> Litteraturbanken se [Notebook](https://github.com/salgo60/open-data-examples/blob/master/Litteraturbanken%20Author.ipynb)   

Tar tacksamt emot tips så att vi får bättre antal poster i Wikidata som matchar LItteraturbanken....

Funderingar
1) Jag städade upp WIkidata så att vi enbart har det ni kallar authorid och inte authorid_norm känns som vårt data blir emklare att underhålla...
2) "Tyvärr" fylls det nog på med authorid_norm från bl.a. vårt verktyg Mix-and-Match se [katalog 1223](https://mix-n-match.toolforge.org/#/catalog/1223) där man kan skapa nya objekt eller matcha med föreslagna...
3) SKBL tittar nu på att dom sätter Qnummer i sitt data --> vore bra om samma sak sker med Littb så matchar vi på det

Status idag 
![image](https://user-images.githubusercontent.com/14206509/94781137-b67eb880-03c9-11eb-96a5-9934d0fa048d.png)
both                    1586
Litterturbanken_only     703
WD_only                    7

**Comment by jroxendal** [comment]
`https://litteraturbanken.se/api/get_author/<authorid>` (ex `https://litteraturbanken.se/api/get_author/S%C3%B6derbergH`).

jag kan tyvärr inte lova att vi kan lägga tid på att manuellt underhålla q-nummer i vår data. är det inte tillräckligt med librisiID?

**Comment by salgo60** [comment]
LIBRIS är perfekt.... det som är problemet med LIBRIS är att dom inte är komplett plus pratar vi Svenskt kvinnobiografiskt lexikon så har dom inte LIBRISnr utan kör ISNI men skall troligen börja ha Wikidata Qnummer även för organisationer etc.... jag körde en [presentation för dom](https://tinyurl.com/SKBLwd) där [Kristoffer Andersson](https://spraakbanken.gu.se/om/personal/kristoffer) hos er?!?!?  var med som skulle fundera på hur det kan implementeras... jag kör liknande synch med SKBL i en [Notebook](https://github.com/salgo60/open-data-examples/blob/master/Svenskt%20Kvinnobiografiskt%20lexikon%20part%203.ipynb)

[SPARQL](https://w.wiki/eck) där vi har Litteraturbanken författare och vilka andra egenskaper vi har på dessa

![image](https://user-images.githubusercontent.com/14206509/95563450-ad22cb00-0a1d-11eb-8c82-282255f82bdf.png)

**Comment by jroxendal** [comment]
man ska inte fundera redan nu på hur det ska generaliseras för att koppla in våra verk också? i så fall ser ju libris forfarande ut som den bästa kandidaten, inte sant?

**Comment by salgo60** [comment]
Japp det är dit jag vill 
* att vi kan ha metadata om era böcker i Wikidata och då är LIBRIS-URI bäst. 
  * att vi kan ha en extern auktoritet utanför är det bästa, för Wikidata "duger" litteraturbanken men då vill vi nog ha lite mera metadata.... annars har jag satt som ambitionsnivå att ha alla författare i Wikidata som ni har LIBRIS id för 
  * säger ni att innehållet i fält som Författare/ Verk/ Libris-id / förlaga/ eid/ Införd / Epub/ Källa är [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) no rights reserved så kan vi importera dom till Wikidata se [Wikidata:Licensing](https://www.wikidata.org/wiki/Wikidata:Licensing) 

Problemet om du frågar mig så är det lite dålig fart på LIBRIS och det blir lite galet att dom inte har unika id:n för alla författare kända som okända... utan har massa textsträngar som inte fungerar bra att ha som referens.... gissar att det bästa vore om Litteraturbanken kunde säga till LIBRIS när dom skall skapa nya auktoriteter..... 

Återkommer gärna om du har ideer ....

**Comment by jroxendal** [comment]
de enda fälten som inte går under CC-0 är författarnas presentationstexter, samt mostsvarande för verk (fast sådana finns inte så många av). resten är fritt fram.

jag förstår att Libris inte är perfekt för vårt ändamål men jag vet inte hur man kommer åt problemet, tyvärr...

**Comment by salgo60** [comment]
Tackar finns det skrivet på någon sida som jag kan referera till?!?!? Wikidata/ WIkipedia är ibland lite av en krigszon så har man inte både hängslen och livrem så överlever man inte till kvällen....

Jag skall idag "hänga" med LIBRIS folk får se om vi kan hitta ett sätt att kommunicera med dom se https://www.kb.se/samverkan-och-utveckling/nytt-fran-kb/nyheter-samverkan-och-utveckling/2020-09-10-webbinarium-om-wikidata.html

**Comment by jroxendal** [comment]
nä det finns inte i pränt (annat än i denna issue nu då) men jag gör en notering om att skriva en sådan sida.
