### ISSUE TITLE
Feedback Wikidata matchning

### ISSUE THREAD

**Issue by salgo60** [spraakbanken/littb-frontend#24]
Skapar denna task med feedback på oklarheter vi hittat i datat när jag matchar med Wikidata

Tanken är att alla författare som Litteraturbanken identifierat med ett LIBRIS-ID skall finnas i Wikidata
* [Jupyter Notebook](https://github.com/salgo60/open-data-examples/blob/master/Litteraturbanken%20Author.ipynb)

**Misstänkta dubbletter**
a) [NordinCG](https://litteraturbanken.se/f%C3%B6rfattare/NordinCG) / [NordinC](https://litteraturbanken.se/f%C3%B6rfattare/NordinC) 
b) [ArfvidssonN](https://litteraturbanken.se/f%C3%B6rfattare/ArfvidssonN) / [ArfwidssonN](https://litteraturbanken.se/f%C3%B6rfattare/ArfwidssonN)   

**Show True**
som jag uppfattar borde vara false eftersom inga böcker finns
* [Eugénie](https://litteraturbanken.se/f%C3%B6rfattare/Eugénie) 
* [BerglindhU](https://litteraturbanken.se/f%C3%B6rfattare/BerglindhU) 
* [EngeströmL](https://litteraturbanken.se/f%C3%B6rfattare/EngeströmL) 
* [Rafael](https://litteraturbanken.se/f%C3%B6rfattare/Rafael) 
* [WestinF](https://litteraturbanken.se/f%C3%B6rfattare/WestinF) 

SPARQL att hämta data från Wikidata
*  https://w.wiki/fmh
* [Video](https://youtu.be/6fLYQKQrgQQ) hur man hämtar detta data

Magnus Sälgö
0705937579

Feedback
* [tweet](https://twitter.com/caialf/status/1314180330497224705?s=20)

**Comment by jroxendal** [comment]
Tjena Magnus! Tack för för hjälpen, felen ska vara åtgärdade nu, minus Berglindh, som har fått ett verk tillagt. vi ska också lösa en redirect eller två framöver, men jag stänger denna issue som fixad.

**Comment by salgo60** [comment]
Tackar skrik till om jag missförstår hur ni använder fälten.... 

Annan tanke är att vi i Wikidata lägger in Litteraturbanken som "beskriven av källa"  [egenskap P1343](https://www.wikidata.org/wiki/Property:P1343) när ni har längre beskrivande texter om författaren ex. Stig Sjödin
* Litt - [Stig Sjödin (1917-1993)](https://litteraturbanken.se/f%C3%B6rfattare/Sj%C3%B6dinS) 
* Wikidata [Q3527629#P1343](https://www.wikidata.org/wiki/Q3527629#P1343)

![image](https://user-images.githubusercontent.com/14206509/95562195-202b4200-0a1c-11eb-94b0-2873fd61c16a.png)

![image](https://user-images.githubusercontent.com/14206509/95562004-d2aed500-0a1b-11eb-81e7-ffdc02c19094.png)

jag har en vag tanke att köra igenom alla era profiler och se hur mycket text som finns på sidan men finns det ett bättre sett att se om ni beskriver författaren så är det bättre

**Comment by jroxendal** [comment]
`https://litteraturbanken.se/api/list_all/author?filter_and={"_exists":"intro"}&to=10000`

**Comment by salgo60** [comment]
@jroxendal en annan grej jag skulle vilja se utvecklas är att när ni nu beskriver Linneaus böcker med platser är att ni i Litteraturbankens data har en ort samma som Wikidata Q nummer och att vi kan ha era böcker i WIkidata och börja beskriva böckerna med länkade data var saker sker och vilka andra saker som beskrivs som ni sedan kan kan hämta "hem" och använda.... Har ni tankar hör av er....

Se [tweet](https://twitter.com/Larissa_Borck/status/1281502542963322882?s=20) hur Semla Lagerlöf bok Nils Holgersson [visualiseras](https://byabbe.se/nils-holgersson-map/#2)
![image](https://user-images.githubusercontent.com/14206509/96362243-37f57b00-112c-11eb-9cba-dabb3c45aef9.png)

* Wikidata
  * verket [Q726254](https://www.wikidata.org/wiki/Q726254?uselang=sv)
    * Upplagor
       *  [Q20160685](https://www.wikidata.org/wiki/Q20160685?uselang=sv) samma som LIBRISXL [5ngc8c1h0k57bpt](https://libris.kb.se/katalogisering/5ngc8c1h0k57bpt) 
       * [Q100528488](https://www.wikidata.org/wiki/Q100528488) Nils Holgerssons underbara resa genom Sverige Bd 1 samma som LIBRISXL [cvn8r75p278q97x](https://libris.kb.se/katalogisering/cvn8r75p278q97x) Littbank [NilsHolgersson1](https://litteraturbanken.se/forfattare/Lagerl%C3%B6fS/titlar/NilsHolgersson1)

SPARQL hämtar från egenskapen [P840 "Utspelar sig på plats"](https://www.wikidata.org/wiki/Property:P840) koordinater för verket Q726254 = https://w.wiki/hNT [video](https://youtu.be/rTUFLRMzBjA)

Variant som [hämtar bilder](https://w.wiki/hNV ) och en som har länk [sv:Wikipedia](https://w.wiki/hNW)
![image](https://user-images.githubusercontent.com/14206509/96363133-9887b680-1132-11eb-954d-80142b705f84.png)

Bra föreläsning om böcker i Wikidata [länk](https://phabricator.wikimedia.org/T237801#5654470) av Martin Poulter (twitter [mlpoulter](https://twitter.com/mlpoulter))

**Comment by jroxendal** [comment]
Jag vill gärna få det där att funka, men jag stötte på problem sist jag kollade närmre på det.

1. jag saknar en listan av relationer (egenskaper) som tar en geografisk punkt som argument. med en sådan lista hade jag kanske kunnat ta fram en delmängd som är relevant för vår data. vi har sådant som 'plats där författare X har varit verksam' eller 'plats nämns i förbifarten på sida Y i verk Z' (vilket är något annat än 'utspelar sig på plats' men den distinktionen kanske inte är så viktig?)
2. de flesta av våra verk finns inte i wikidata, så relationer av typen R(plats, verk) låter sig då inte enkelt fångas utan att först lägga till verket, inbillar jag mig? Eller ska jag försöka gå igenom libris?
3. flera artiklar handlar om personer som inte finns i litteraturbankens persongalleri, men där kan jag förstås lägga till Q-nummer istället. 

ang. persistent identifierare: nog duger väl latitud+longitud som persistent identifierare?

**Comment by salgo60** [comment]
Jag tar gärna en diskussion om du vill eller så pratar vi online... jag finns just nu på https://meet.wmcloud.org/Wikidata-SV eller nås på 0705937579 ---- vi snackar mycket WIkidata på en Telegram grupp "Wikidata Sverige" [invite link](https://t.me/joinchat/FgDj6BTRqdKkYZaCqOB_FA) där folk bättre en mig kan dyka upp och hjälpa till just nu är det fokus på Riksdagsdokument och SFS:er och oppositionsråd i kommuner minst sagt spretigt ....

En variant som jag ser det är att du skapa det du kallar **Litteraturbanken:place** kollar du på Uppsala Universitet Alvin så har dom en [Wikidata egenskap hos oss P6821](https://phabricator.wikimedia.org/T225522) som jag kopplat ihop 24000 ggr men hos dom kvalificerar dom sina id:n med
alvin-place: exempel [karta med koordinater](https://w.wiki/4vE) från WIkidata där ex. Vitön = WD [Q851568](https://www.wikidata.org/wiki/Q851568)

![image](https://user-images.githubusercontent.com/14206509/96440742-ad367e00-1208-11eb-90e2-fc6031a3ce5b.png)


alvin-person: exempelvis [alvin-person:2963](http://www.alvin-portal.org/alvin/view.jsf?pid=alvin-person%3A2963&dswid=4396) är samma som [Q6015644](https://www.wikidata.org/wiki/Q6015644)
alvin-organisation...

min tanke är att du har ett persistent nummer och säger att detta är plats  numer xxx sedan kopplar du dig till en plats i Wikidata som finns och "knycker" all metadata du behöver och har Qnummer kopplingen hos dig.... om du hittar det i WIkidata så skapar du bara det hos dig så skapar vi det hos oss...


```
<placeid>1</placeid>
<namn lang="sv">Vargfällan bråten</namn>
<coord>
<relationer>
     har får man koppla platsen till boken och jag gissar bokid/ sida/ ?!?!?

```
Sedan är det som du säger att när vi har era böckerna hos oss så kan vi börja skjuta data fram och tillbaka... men som sagt Wikidata är en Wiki så hittar du bra folk så blir datat bra annars kan det bli lite galet... vi skalar ju till > 200 språk och tar ju sats för att automatgenerera artiklar från metadata i ett nytt projekt [Abstrakt Wikipedia](https://en.wikipedia.org/wiki/Abstract_Wikipedia) så man vet nog aldrig var detta hamnar. Jag ser det som ett kul socialt experiment ;-) ...

**Comment by salgo60** [comment]
**Kommunikation** såg denna task [T266431](https://phabricator.wikimedia.org/T266431) gissar att några har en dialog bara som en info så lever Wikimedia Sverige lite utanför oss som är aktiva på Wikidata/Wikipedia vilket känns väldigt dysfunktionellt så ha överseende att den ene inte vet vad den andre gör....

**Mina tasks:**
* kör Notebook dagligen som uppdaterar författare i Wikidata... ställde fråga till Alicia om hennes planer [länk T267081](https://phabricator.wikimedia.org/T267081) vi får se om hon orkar svara det brukar vara lite si och så med detta ... 
* testade detta med att placera en bok "Nils Holgersson..:" på en karta dvs. denna issue
* försöka matcha så många författare hos LItteraturbanken dvs. [mix.and.match](https://mix-n-match.toolforge.org/#/catalog/1223)
* testade att begära en [egenskap för inträdestal i WD](https://www.wikidata.org/w/index.php?title=Wikidata:Property_proposal/Inaugural_address) men det känns tvivelaktigt om det blir av

Skrik till om något känns fel jag nås på
0705937579
salgo60@msn.com

**Comment by jroxendal** [comment]
Hej! Jag hinner inte kika på detta just nu, men återkommer i nästa vecka med lite tankar!
